import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const parseNuhil = (file) => {
  const data = JSON.parse(fs.readFileSync(path.join(__dirname, 'data', file), 'utf8'));
  return data[2].data;
};

const divisions = parseNuhil('divisions.json');
const districts = parseNuhil('districts.json');
const upazilas = parseNuhil('upazilas.json');
const unions = parseNuhil('unions.json');

const tsContent = `// Auto-generated by generate-locations-ts.mjs
export const bdDivisions = ${JSON.stringify(divisions, null, 2)};
export const bdDistricts = ${JSON.stringify(districts, null, 2)};
export const bdUpazilas = ${JSON.stringify(upazilas, null, 2)};
export const bdUnions = ${JSON.stringify(unions, null, 2)};
`;

fs.writeFileSync(path.join(__dirname, 'data', 'locations.data.ts'), tsContent);
console.log('Created locations.data.ts');
