import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1790406745498 implements MigrationInterface {
    name = 'InitialSchema1790406745498'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_48ce552495d14eae9b187bb6716" UNIQUE ("name"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."roles_name_enum" AS ENUM('SUPER_ADMIN', 'ADMIN', 'SELLER', 'RIDER', 'CUSTOMER')`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" "public"."roles_name_enum" NOT NULL, "description" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'BLOCKED', 'PENDING')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "phone" character varying NOT NULL, "email" character varying, "passwordHash" character varying, "firstName" character varying, "lastName" character varying, "status" "public"."users_status_enum" NOT NULL DEFAULT 'PENDING', "isPhoneVerified" boolean NOT NULL DEFAULT false, "isEmailVerified" boolean NOT NULL DEFAULT false, "avatar" character varying, "refreshTokenHash" character varying, "lastLoginAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "UQ_a000cca60bcf04454e727699490" UNIQUE ("phone"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "parent_id" uuid, "name_en" character varying(150) NOT NULL, "name_bn" character varying(200) NOT NULL, "slug" character varying NOT NULL, "icon" character varying, "image" character varying, "description_en" text, "description_bn" text, "sort_order" integer NOT NULL DEFAULT '0', "is_regulated" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_420d9f679d41281f282f5bc7d09" UNIQUE ("slug"), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "brands" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name_en" character varying(150) NOT NULL, "name_bn" character varying(200) NOT NULL, "slug" character varying NOT NULL, "logo" character varying, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_b15428f362be2200922952dc268" UNIQUE ("slug"), CONSTRAINT "PK_b0c437120b624da1034a81fc561" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_variants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "name_en" character varying(150) NOT NULL, "name_bn" character varying(200) NOT NULL, "sku" character varying NOT NULL, "images" jsonb, "attributes" jsonb, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_46f236f21640f9da218a063a866" UNIQUE ("sku"), CONSTRAINT "PK_281e3f2c55652d6a22c0aa59fd7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_images" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "url" character varying(500) NOT NULL, "storage_path" character varying(500) NOT NULL, "filename" character varying(255) NOT NULL, "original_filename" character varying(255), "mime_type" character varying(100) NOT NULL, "size_bytes" integer NOT NULL DEFAULT '0', "is_primary" boolean NOT NULL DEFAULT false, "sort_order" integer NOT NULL DEFAULT '0', "alt_text" character varying(255), "source_url" text, "source_attribution" character varying(500), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1974264ea7265989af8392f63a1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."products_status_enum" AS ENUM('DRAFT', 'PENDING_REVIEW', 'PENDING_APPROVAL', 'PUBLISHED', 'ACTIVE', 'UNPUBLISHED', 'INACTIVE', 'ARCHIVED')`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "category_id" uuid NOT NULL, "sub_category_id" uuid, "brand_id" uuid, "name_en" character varying(255) NOT NULL, "name_bn" character varying(255) NOT NULL, "slug" character varying NOT NULL, "short_description_en" text, "short_description_bn" text, "description_en" text, "description_bn" text, "sku" character varying(100), "barcode" character varying(100), "price" numeric(10,2), "compare_at_price" numeric(10,2), "stock" integer NOT NULL DEFAULT '0', "unit" character varying(50), "status" "public"."products_status_enum" NOT NULL DEFAULT 'DRAFT', "is_featured" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "source" character varying(50), "source_product_id" character varying(100), "source_url" text, "source_price" numeric(10,2), "source_currency" character varying(10), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_464f927ae360106b783ed0b4106" UNIQUE ("slug"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "wishlist_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "product_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e0584a3664156caa678765afadc" UNIQUE ("user_id", "product_id"), CONSTRAINT "PK_0bd52924a97cda208ed2a07bd69" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."wallet_transactions_type_enum" AS ENUM('CREDIT', 'DEBIT')`);
        await queryRunner.query(`CREATE TABLE "wallet_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "wallet_id" uuid NOT NULL, "type" "public"."wallet_transactions_type_enum" NOT NULL, "amount" numeric(12,2) NOT NULL, "description" character varying(255) NOT NULL, "reference_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5120f131bde2cda940ec1a621db" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "wallets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "balance" numeric(12,2) NOT NULL DEFAULT '0', "pending_clearance" numeric(12,2) NOT NULL DEFAULT '0', "total_earned" numeric(12,2) NOT NULL DEFAULT '0', "total_withdrawn" numeric(12,2) NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_92558c08091598f7a4439586cda" UNIQUE ("user_id"), CONSTRAINT "REL_92558c08091598f7a4439586cd" UNIQUE ("user_id"), CONSTRAINT "PK_8402e5df5a30a229380e83e4f7e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "shops" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "seller_id" uuid NOT NULL, "name_en" character varying(150) NOT NULL, "name_bn" character varying(200) NOT NULL, "slug" character varying NOT NULL, "short_description" character varying(500), "description" text, "logo" character varying, "banner" character varying, "phone" character varying(30), "secondary_phone" character varying(30), "whatsapp" character varying(30), "email" character varying(150), "website" character varying(255), "facebook" character varying(255), "instagram" character varying(255), "address" text, "area" character varying(100), "district" character varying(100), "upazila" character varying(100), "union" character varying(100), "village" character varying(100), "latitude" numeric(10,7), "longitude" numeric(10,7), "opening_hours" character varying(200), "delivery_info" text, "is_verified" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8c28ec876676eeb1dcb65c01b7f" UNIQUE ("slug"), CONSTRAINT "PK_3c6aaa6607d287de99815e60b96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "platform_settings" ("key" character varying(100) NOT NULL, "value" text NOT NULL, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5d9031e30fac3ec3ec8b9602e17" PRIMARY KEY ("key"))`);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "user_id" uuid NOT NULL, "rating" integer NOT NULL, "comment" text, "is_approved" boolean NOT NULL DEFAULT true, "images" text array, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."product_request_history_status_enum" AS ENUM('PENDING', 'REVIEWING', 'SEARCHING', 'FOUND', 'PRODUCT_ADDED', 'CUSTOMER_NOTIFIED', 'CLOSED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "product_request_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_request_id" uuid NOT NULL, "status" "public"."product_request_history_status_enum" NOT NULL, "remark" text, "changed_by_user_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7b90286bf685f4534037e34ada7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."product_requests_status_enum" AS ENUM('PENDING', 'REVIEWING', 'SEARCHING', 'FOUND', 'PRODUCT_ADDED', 'CUSTOMER_NOTIFIED', 'CLOSED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "product_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "requested_product_name" character varying NOT NULL, "description" text, "preferred_information" text, "status" "public"."product_requests_status_enum" NOT NULL DEFAULT 'PENDING', "linked_product_id" uuid, "admin_notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_95548600cf27dcc824033dea8cd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payout_requests_method_enum" AS ENUM('BANK_TRANSFER', 'BKASH', 'NAGAD', 'ROCKET')`);
        await queryRunner.query(`CREATE TYPE "public"."payout_requests_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "payout_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "seller_id" uuid NOT NULL, "amount" numeric(12,2) NOT NULL, "method" "public"."payout_requests_method_enum" NOT NULL, "account_details" text NOT NULL, "status" "public"."payout_requests_status_enum" NOT NULL DEFAULT 'PENDING', "admin_note" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3a6acb302f56ad7dadda35c86b8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inventory" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "seller_product_id" uuid NOT NULL, "quantity" integer NOT NULL DEFAULT '0', "reserved_quantity" integer NOT NULL DEFAULT '0', "low_stock_threshold" integer NOT NULL DEFAULT '5', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_89d3fb68538d89f1c1a6517ebe" UNIQUE ("seller_product_id"), CONSTRAINT "PK_82aa5da437c5bbfb80703b08309" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "seller_products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "shop_id" uuid NOT NULL, "product_variant_id" uuid NOT NULL, "price" numeric(10,2) NOT NULL, "discount_price" numeric(10,2), "seller_sku" character varying, "is_regulated_approved" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0efaba257e14cf3313664849ff9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "seller_product_id" uuid NOT NULL, "quantity" integer NOT NULL, "unit_price" numeric(10,2) NOT NULL, "subtotal" numeric(10,2) NOT NULL, CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."order_status_history_from_status_enum" AS ENUM('PENDING', 'CONFIRMED', 'PROCESSING', 'READY_FOR_PICKUP', 'PICKED_UP', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'FAILED')`);
        await queryRunner.query(`CREATE TYPE "public"."order_status_history_status_enum" AS ENUM('PENDING', 'CONFIRMED', 'PROCESSING', 'READY_FOR_PICKUP', 'PICKED_UP', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'FAILED')`);
        await queryRunner.query(`CREATE TYPE "public"."order_status_history_to_status_enum" AS ENUM('PENDING', 'CONFIRMED', 'PROCESSING', 'READY_FOR_PICKUP', 'PICKED_UP', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "order_status_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "from_status" "public"."order_status_history_from_status_enum", "status" "public"."order_status_history_status_enum" NOT NULL, "to_status" "public"."order_status_history_to_status_enum", "changed_by_user_id" uuid, "changed_by_role" character varying, "remark" text, "reason" text, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e6c66d853f155531985fc4f6ec8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "areas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "union_id" uuid NOT NULL, "name_en" character varying(100) NOT NULL, "name_bn" character varying(150) NOT NULL, "delivery_fee" numeric(10,2) NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5110493f6342f34c978c084d0d6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "unions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "upazila_id" uuid NOT NULL, "name_en" character varying(100) NOT NULL, "name_bn" character varying(150) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_97b35789dd5101a3e05e4f4eced" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "upazilas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "district_id" uuid NOT NULL, "name_en" character varying(100) NOT NULL, "name_bn" character varying(150) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ab2d8d9c35677f393b9fc6d8ce7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "districts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "division_id" uuid NOT NULL, "name_en" character varying(100) NOT NULL, "name_bn" character varying(150) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_972a72ff4e3bea5c7f43a2b98af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "divisions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "country_id" uuid NOT NULL, "name_en" character varying(100) NOT NULL, "name_bn" character varying(150) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c1f864477b3fd0954564108ed96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "countries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name_en" character varying(100) NOT NULL, "name_bn" character varying(150) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b2d7006793e8697ab3ae2deff18" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "addresses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "title" character varying(100) NOT NULL, "contact_name" character varying(150) NOT NULL, "contact_phone" character varying(20) NOT NULL, "country_id" uuid, "division_id" uuid, "district_id" uuid, "upazila_id" uuid, "union_id" uuid, "area_id" uuid, "street_address" text NOT NULL, "lat" numeric(10,8), "lng" numeric(11,8), "is_default" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_745d8f43d3af10ab8247465e450" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('PENDING', 'CONFIRMED', 'PROCESSING', 'READY_FOR_PICKUP', 'PICKED_UP', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'FAILED')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_payment_method_enum" AS ENUM('COD', 'ONLINE')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_payment_status_enum" AS ENUM('PENDING', 'PAID', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "address_id" uuid NOT NULL, "subtotal" numeric(10,2) NOT NULL, "delivery_fee" numeric(10,2) NOT NULL DEFAULT '0', "discount" numeric(10,2) NOT NULL DEFAULT '0', "total" numeric(10,2) NOT NULL, "status" "public"."orders_status_enum" NOT NULL DEFAULT 'PENDING', "payment_method" "public"."orders_payment_method_enum" NOT NULL DEFAULT 'COD', "payment_status" "public"."orders_payment_status_enum" NOT NULL DEFAULT 'PENDING', "transaction_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('PENDING', 'INITIATED', 'PROCESSING', 'PAID', 'FAILED', 'CANCELLED', 'EXPIRED', 'REFUNDED', 'PARTIALLY_REFUNDED')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "user_id" uuid NOT NULL, "provider" character varying(50) NOT NULL DEFAULT 'SSLCOMMERZ', "transaction_id" character varying(100) NOT NULL, "amount" numeric(10,2) NOT NULL, "currency" character varying(10) NOT NULL DEFAULT 'BDT', "status" "public"."payments_status_enum" NOT NULL DEFAULT 'INITIATED', "gateway_status" character varying(50), "validation_id" character varying(100), "bank_transaction_id" character varying(100), "risk_level" character varying(20), "risk_title" character varying(100), "card_type" character varying(100), "card_brand" character varying(100), "card_issuer" character varying(100), "gateway_response" jsonb, "paid_at" TIMESTAMP, "failed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_3c324ca49dabde7ffc0ef64675d" UNIQUE ("transaction_id"), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b2f7b823a21562eeca20e72b00" ON "payments" ("order_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_427785468fb7d2733f59e7d7d3" ON "payments" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3c324ca49dabde7ffc0ef64675" ON "payments" ("transaction_id") `);
        await queryRunner.query(`CREATE TABLE "otps" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "phone" character varying NOT NULL, "code" character varying NOT NULL, "attempts" integer NOT NULL DEFAULT '0', "expiresAt" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_91fef5ed60605b854a2115d2410" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_33206384cc0a56e1d8d0a0cc47" ON "otps" ("phone") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('ORDER_UPDATE', 'SYSTEM', 'PROMO', 'REQUEST')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "title" character varying(255) NOT NULL, "message" text NOT NULL, "type" "public"."notifications_type_enum" NOT NULL DEFAULT 'SYSTEM', "is_read" boolean NOT NULL DEFAULT false, "read_at" TIMESTAMP, "data" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "flash_sales" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "startDate" TIMESTAMP NOT NULL, "endDate" TIMESTAMP NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "bannerImage" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_70299593044ffcba05cc30b97dc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "flash_sale_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "flashSaleId" uuid NOT NULL, "sellerProductId" uuid NOT NULL, "discountPrice" numeric(10,2) NOT NULL, "quantityAvailable" integer NOT NULL DEFAULT '0', "quantitySold" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f7be2cbf28d0924336b0d91369a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."disputes_reason_enum" AS ENUM('DAMAGED', 'MISSING_ITEM', 'NOT_AS_DESCRIBED', 'WRONG_ITEM', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."disputes_status_enum" AS ENUM('OPEN', 'UNDER_REVIEW', 'RESOLVED_REFUNDED', 'RESOLVED_REJECTED')`);
        await queryRunner.query(`CREATE TABLE "disputes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orderId" uuid NOT NULL, "customerId" uuid NOT NULL, "sellerId" uuid NOT NULL, "reason" "public"."disputes_reason_enum" NOT NULL, "description" text NOT NULL, "evidenceImages" jsonb, "status" "public"."disputes_status_enum" NOT NULL DEFAULT 'OPEN', "adminDecision" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3c97580d01c1a4b0b345c42a107" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."deliveries_status_enum" AS ENUM('UNASSIGNED', 'ASSIGNED', 'ACCEPTED', 'PICKED_UP', 'OUT_FOR_DELIVERY', 'DELIVERED', 'FAILED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "deliveries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "rider_id" uuid, "status" "public"."deliveries_status_enum" NOT NULL DEFAULT 'UNASSIGNED', "assigned_at" TIMESTAMP, "pickup_time" TIMESTAMP, "delivery_time" TIMESTAMP, "notes" text, "current_lat" numeric(10,8), "current_lng" numeric(11,8), "last_location_updated_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_789dba7900f6d25550280ad3b93" UNIQUE ("order_id"), CONSTRAINT "REL_789dba7900f6d25550280ad3b9" UNIQUE ("order_id"), CONSTRAINT "PK_a6ef225c5c5f0974e503bfb731f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "dispute_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "disputeId" uuid NOT NULL, "senderId" uuid NOT NULL, "senderRole" character varying NOT NULL, "message" text NOT NULL, "attachment" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8826f78d556a1846f8cbad5ed05" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."coupons_discounttype_enum" AS ENUM('FIXED', 'PERCENTAGE')`);
        await queryRunner.query(`CREATE TABLE "coupons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "discountType" "public"."coupons_discounttype_enum" NOT NULL DEFAULT 'FIXED', "discountValue" numeric(10,2) NOT NULL, "minOrderAmount" numeric(10,2) NOT NULL DEFAULT '0', "maxDiscountAmount" numeric(10,2), "startDate" TIMESTAMP, "endDate" TIMESTAMP, "usageLimit" integer, "usedCount" integer NOT NULL DEFAULT '0', "customerUsageLimit" integer NOT NULL DEFAULT '1', "isActive" boolean NOT NULL DEFAULT true, "shopId" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e025109230e82925843f2a14c48" UNIQUE ("code"), CONSTRAINT "PK_d7ea8864a0150183770f3e9a8cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."delivery_status_history_status_enum" AS ENUM('UNASSIGNED', 'ASSIGNED', 'ACCEPTED', 'PICKED_UP', 'OUT_FOR_DELIVERY', 'DELIVERED', 'FAILED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "delivery_status_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "delivery_id" uuid NOT NULL, "status" "public"."delivery_status_history_status_enum" NOT NULL, "changed_by_id" uuid, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6d5a3b1c231e2e87c93d6a7cb44" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "coupon_usages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "coupon_id" uuid NOT NULL, "user_id" uuid NOT NULL, "order_id" uuid, "discount_amount" numeric(10,2) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_01ff9a1cac559c4ae2e4179d0a3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "conversations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "referenceId" character varying, "referenceType" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ee34f4f7ced4ec8681f26bf04ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" text NOT NULL, "messageType" character varying NOT NULL DEFAULT 'TEXT', "senderRole" character varying, "sender_id" uuid NOT NULL, "conversation_id" uuid NOT NULL, "isRead" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "actor_id" uuid, "actor_name" character varying(200), "action" character varying(100) NOT NULL, "target_type" character varying(100), "target_id" character varying(100), "details" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_177183f29f438c488b5e8510cd" ON "audit_logs" ("actor_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE TABLE "banners" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(200) NOT NULL, "image_url" character varying NOT NULL, "link_url" character varying, "is_active" boolean NOT NULL DEFAULT true, "display_order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e9b186b959296fcb940790d31c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."seller_applications_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "seller_applications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "shop_name_en" character varying(150) NOT NULL, "shop_name_bn" character varying(200) NOT NULL, "shop_slug" character varying(150) NOT NULL, "phone" character varying(20) NOT NULL, "email" character varying(150), "description" text, "address" text, "trade_license_number" character varying(100), "nid_number" character varying(50), "status" "public"."seller_applications_status_enum" NOT NULL DEFAULT 'PENDING', "admin_notes" text, "reviewer_id" uuid, "reviewed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_203be9b9b1f8ff560e8af1f90a5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."demand_events_eventtype_enum" AS ENUM('VIEW', 'SEARCH', 'ADD_TO_CART', 'WISHLIST', 'REQUEST', 'PURCHASE')`);
        await queryRunner.query(`CREATE TABLE "demand_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "eventType" "public"."demand_events_eventtype_enum" NOT NULL, "userId" uuid, "productId" uuid, "categoryId" uuid, "searchQuery" character varying, "productRequestId" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_edc6dec8416aeb8dd466a059c68" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_013ab4bb41831e4684f2f498a6" ON "demand_events" ("eventType") `);
        await queryRunner.query(`CREATE INDEX "IDX_814d79bca04105047c96ae13b8" ON "demand_events" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a92777f7512b1712b617dfccad" ON "demand_events" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e3f54c991749da6667c10b9ec9" ON "demand_events" ("categoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c13f2e6f1db742e645b919721a" ON "demand_events" ("productRequestId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e21c5e12c69727386fb27500dd" ON "demand_events" ("created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."rider_applications_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "rider_applications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "full_name" character varying(150) NOT NULL, "phone" character varying(20) NOT NULL, "email" character varying(150), "nid_number" character varying(50) NOT NULL, "vehicle_type" character varying(50) NOT NULL DEFAULT 'BIKE', "vehicle_plate_number" character varying(100), "driving_license_number" character varying(100), "preferred_zone" character varying(150), "emergency_contact" character varying(50), "status" "public"."rider_applications_status_enum" NOT NULL DEFAULT 'PENDING', "admin_notes" text, "reviewer_id" uuid, "reviewed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_28a54be5407d09e5cd8af23a46b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."import_logs_mode_enum" AS ENUM('DRY_RUN', 'IMPORT', 'RETRY_IMAGES')`);
        await queryRunner.query(`CREATE TYPE "public"."import_logs_status_enum" AS ENUM('RUNNING', 'COMPLETED', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "import_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "source" character varying(50) NOT NULL, "mode" "public"."import_logs_mode_enum" NOT NULL DEFAULT 'IMPORT', "status" "public"."import_logs_status_enum" NOT NULL DEFAULT 'RUNNING', "total_fetched" integer NOT NULL DEFAULT '0', "created_count" integer NOT NULL DEFAULT '0', "updated_count" integer NOT NULL DEFAULT '0', "skipped_count" integer NOT NULL DEFAULT '0', "duplicates_count" integer NOT NULL DEFAULT '0', "failed_count" integer NOT NULL DEFAULT '0', "image_failures_count" integer NOT NULL DEFAULT '0', "mapping_failures_count" integer NOT NULL DEFAULT '0', "error_summary" text, "details" jsonb, "started_at" TIMESTAMP WITH TIME ZONE NOT NULL, "completed_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_605638f3d14c87ce06601313f0e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("user_id" uuid NOT NULL, "role_id" uuid NOT NULL, CONSTRAINT "PK_23ed6f04fe43066df08379fd034" PRIMARY KEY ("user_id", "role_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_87b8888186ca9769c960e92687" ON "user_roles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b23c65e50a758245a33ee35fda" ON "user_roles" ("role_id") `);
        await queryRunner.query(`CREATE TABLE "category_brands" ("brand_id" uuid NOT NULL, "category_id" uuid NOT NULL, CONSTRAINT "PK_3b12319bad97cae378c4f521387" PRIMARY KEY ("brand_id", "category_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dcb5e8a55a4180e383aafdb193" ON "category_brands" ("brand_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0f2577d3e847475ecf0f9aefdb" ON "category_brands" ("category_id") `);
        await queryRunner.query(`CREATE TABLE "conversation_participants" ("conversation_id" uuid NOT NULL, "user_id" uuid NOT NULL, CONSTRAINT "PK_fdcd6405d74e797f10fa8360338" PRIMARY KEY ("conversation_id", "user_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1559e8a16b828f2e836a231280" ON "conversation_participants" ("conversation_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_377d4041a495b81ee1a85ae026" ON "conversation_participants" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_88cea2dc9c31951d06437879b40" FOREIGN KEY ("parent_id") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_6343513e20e2deab45edfce1316" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD CONSTRAINT "FK_4f166bb8c2bfcef2498d97b4068" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_9a5f6868c96e0069e699f33e124" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_3fffb0be83ac483af3a55f41170" FOREIGN KEY ("sub_category_id") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_1530a6f15d3c79d1b70be98f2be" FOREIGN KEY ("brand_id") REFERENCES "brands"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wishlist_items" ADD CONSTRAINT "FK_549f44d8b756e2690deb099f83b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wishlist_items" ADD CONSTRAINT "FK_177397e044732e7e9c0215cd5b7" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD CONSTRAINT "FK_c57d19129968160f4db28fc8b28" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_92558c08091598f7a4439586cda" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shops" ADD CONSTRAINT "FK_24acfab664c1ee213d7b9afac9c" FOREIGN KEY ("seller_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_9482e9567d8dcc2bc615981ef44" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_728447781a30bc3fcfe5c2f1cdf" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_request_history" ADD CONSTRAINT "FK_318eedd1c453ea8ec1cc470650e" FOREIGN KEY ("product_request_id") REFERENCES "product_requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_request_history" ADD CONSTRAINT "FK_f5854387110a5fc7780853b5796" FOREIGN KEY ("changed_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_requests" ADD CONSTRAINT "FK_c7059212b768f76435cced0b2dd" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_requests" ADD CONSTRAINT "FK_037ecf1bc89e6345512e996f7c3" FOREIGN KEY ("linked_product_id") REFERENCES "products"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payout_requests" ADD CONSTRAINT "FK_3ef419037249b077dc92d4aff26" FOREIGN KEY ("seller_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD CONSTRAINT "FK_89d3fb68538d89f1c1a6517ebe0" FOREIGN KEY ("seller_product_id") REFERENCES "seller_products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seller_products" ADD CONSTRAINT "FK_14e70742d19396508975a0fcdaa" FOREIGN KEY ("shop_id") REFERENCES "shops"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seller_products" ADD CONSTRAINT "FK_7023230fa26e66dbbd85329e471" FOREIGN KEY ("product_variant_id") REFERENCES "product_variants"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_145532db85752b29c57d2b7b1f1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_cb09242a622007b0c0bd5497a94" FOREIGN KEY ("seller_product_id") REFERENCES "seller_products"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_status_history" ADD CONSTRAINT "FK_1ca7d5228cf9dc589b60243933c" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "areas" ADD CONSTRAINT "FK_351582e1a0d6082c7afffbcb48c" FOREIGN KEY ("union_id") REFERENCES "unions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unions" ADD CONSTRAINT "FK_fe9cc1eb5a2e33a6c25f6b81985" FOREIGN KEY ("upazila_id") REFERENCES "upazilas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "upazilas" ADD CONSTRAINT "FK_e04fa8599f5eea91baf26fbbfdb" FOREIGN KEY ("district_id") REFERENCES "districts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "districts" ADD CONSTRAINT "FK_b0f53665358e2fee2fd290d115f" FOREIGN KEY ("division_id") REFERENCES "divisions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "divisions" ADD CONSTRAINT "FK_469211a0a03cf8dc332c7655dbb" FOREIGN KEY ("country_id") REFERENCES "countries"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD CONSTRAINT "FK_16aac8a9f6f9c1dd6bcb75ec023" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD CONSTRAINT "FK_98e1ca336038167c7eb48c02582" FOREIGN KEY ("country_id") REFERENCES "countries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD CONSTRAINT "FK_8501950a64247eb15c7cab9a2b7" FOREIGN KEY ("division_id") REFERENCES "divisions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD CONSTRAINT "FK_444b34460fc67bd002be612d53f" FOREIGN KEY ("district_id") REFERENCES "districts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD CONSTRAINT "FK_7d46aeb66d671008e0ae07592fe" FOREIGN KEY ("upazila_id") REFERENCES "upazilas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD CONSTRAINT "FK_9e65510985e88a80e461f6801d3" FOREIGN KEY ("union_id") REFERENCES "unions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD CONSTRAINT "FK_9745bf67ca9cb4a4244e90fb7a0" FOREIGN KEY ("area_id") REFERENCES "areas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_a922b820eeef29ac1c6800e826a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_d39c53244703b8534307adcd073" FOREIGN KEY ("address_id") REFERENCES "addresses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_b2f7b823a21562eeca20e72b006" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_427785468fb7d2733f59e7d7d39" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flash_sale_items" ADD CONSTRAINT "FK_22e50748cc477cdda44501c2b7c" FOREIGN KEY ("flashSaleId") REFERENCES "flash_sales"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flash_sale_items" ADD CONSTRAINT "FK_ce6c9fd26e8c5c970fa04f5ad06" FOREIGN KEY ("sellerProductId") REFERENCES "seller_products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disputes" ADD CONSTRAINT "FK_8acbc1c3c0ba479dd4010eeb46a" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disputes" ADD CONSTRAINT "FK_4973306692b39c7e6084a8ac546" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disputes" ADD CONSTRAINT "FK_1f17253f54a59ef6272fba84d91" FOREIGN KEY ("sellerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD CONSTRAINT "FK_789dba7900f6d25550280ad3b93" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD CONSTRAINT "FK_e4ca3c1d4c3c348818b524a071a" FOREIGN KEY ("rider_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dispute_messages" ADD CONSTRAINT "FK_288e9a3fe13cfe14abe9824e9ce" FOREIGN KEY ("disputeId") REFERENCES "disputes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dispute_messages" ADD CONSTRAINT "FK_e154dd9c8d78610a275b5c72536" FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_status_history" ADD CONSTRAINT "FK_a0bef167f7ecc0ba4a7d80fa5c5" FOREIGN KEY ("delivery_id") REFERENCES "deliveries"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_status_history" ADD CONSTRAINT "FK_0d6a5cf61488ba621cc4c110407" FOREIGN KEY ("changed_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupon_usages" ADD CONSTRAINT "FK_56491a0d0010feb079b964e23b4" FOREIGN KEY ("coupon_id") REFERENCES "coupons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupon_usages" ADD CONSTRAINT "FK_579f1e1f0ccf35785bbbdebeb85" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupon_usages" ADD CONSTRAINT "FK_f017af60a02209a6b045f673ca1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_22133395bd13b970ccd0c34ab22" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_3bc55a7c3f9ed54b520bb5cfe23" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seller_applications" ADD CONSTRAINT "FK_b25f3c1be9f3510bd45fcf688b9" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seller_applications" ADD CONSTRAINT "FK_6753be77b932081c646b591ff1a" FOREIGN KEY ("reviewer_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rider_applications" ADD CONSTRAINT "FK_a2dac5f05ccdb131542ec48d67b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rider_applications" ADD CONSTRAINT "FK_adb74d5437e6b073dab3eb299c6" FOREIGN KEY ("reviewer_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "category_brands" ADD CONSTRAINT "FK_dcb5e8a55a4180e383aafdb1937" FOREIGN KEY ("brand_id") REFERENCES "brands"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "category_brands" ADD CONSTRAINT "FK_0f2577d3e847475ecf0f9aefdb4" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" ADD CONSTRAINT "FK_1559e8a16b828f2e836a2312800" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" ADD CONSTRAINT "FK_377d4041a495b81ee1a85ae026f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "conversation_participants" DROP CONSTRAINT "FK_377d4041a495b81ee1a85ae026f"`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" DROP CONSTRAINT "FK_1559e8a16b828f2e836a2312800"`);
        await queryRunner.query(`ALTER TABLE "category_brands" DROP CONSTRAINT "FK_0f2577d3e847475ecf0f9aefdb4"`);
        await queryRunner.query(`ALTER TABLE "category_brands" DROP CONSTRAINT "FK_dcb5e8a55a4180e383aafdb1937"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "rider_applications" DROP CONSTRAINT "FK_adb74d5437e6b073dab3eb299c6"`);
        await queryRunner.query(`ALTER TABLE "rider_applications" DROP CONSTRAINT "FK_a2dac5f05ccdb131542ec48d67b"`);
        await queryRunner.query(`ALTER TABLE "seller_applications" DROP CONSTRAINT "FK_6753be77b932081c646b591ff1a"`);
        await queryRunner.query(`ALTER TABLE "seller_applications" DROP CONSTRAINT "FK_b25f3c1be9f3510bd45fcf688b9"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_3bc55a7c3f9ed54b520bb5cfe23"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_22133395bd13b970ccd0c34ab22"`);
        await queryRunner.query(`ALTER TABLE "coupon_usages" DROP CONSTRAINT "FK_f017af60a02209a6b045f673ca1"`);
        await queryRunner.query(`ALTER TABLE "coupon_usages" DROP CONSTRAINT "FK_579f1e1f0ccf35785bbbdebeb85"`);
        await queryRunner.query(`ALTER TABLE "coupon_usages" DROP CONSTRAINT "FK_56491a0d0010feb079b964e23b4"`);
        await queryRunner.query(`ALTER TABLE "delivery_status_history" DROP CONSTRAINT "FK_0d6a5cf61488ba621cc4c110407"`);
        await queryRunner.query(`ALTER TABLE "delivery_status_history" DROP CONSTRAINT "FK_a0bef167f7ecc0ba4a7d80fa5c5"`);
        await queryRunner.query(`ALTER TABLE "dispute_messages" DROP CONSTRAINT "FK_e154dd9c8d78610a275b5c72536"`);
        await queryRunner.query(`ALTER TABLE "dispute_messages" DROP CONSTRAINT "FK_288e9a3fe13cfe14abe9824e9ce"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP CONSTRAINT "FK_e4ca3c1d4c3c348818b524a071a"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP CONSTRAINT "FK_789dba7900f6d25550280ad3b93"`);
        await queryRunner.query(`ALTER TABLE "disputes" DROP CONSTRAINT "FK_1f17253f54a59ef6272fba84d91"`);
        await queryRunner.query(`ALTER TABLE "disputes" DROP CONSTRAINT "FK_4973306692b39c7e6084a8ac546"`);
        await queryRunner.query(`ALTER TABLE "disputes" DROP CONSTRAINT "FK_8acbc1c3c0ba479dd4010eeb46a"`);
        await queryRunner.query(`ALTER TABLE "flash_sale_items" DROP CONSTRAINT "FK_ce6c9fd26e8c5c970fa04f5ad06"`);
        await queryRunner.query(`ALTER TABLE "flash_sale_items" DROP CONSTRAINT "FK_22e50748cc477cdda44501c2b7c"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_427785468fb7d2733f59e7d7d39"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_b2f7b823a21562eeca20e72b006"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_d39c53244703b8534307adcd073"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_a922b820eeef29ac1c6800e826a"`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP CONSTRAINT "FK_9745bf67ca9cb4a4244e90fb7a0"`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP CONSTRAINT "FK_9e65510985e88a80e461f6801d3"`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP CONSTRAINT "FK_7d46aeb66d671008e0ae07592fe"`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP CONSTRAINT "FK_444b34460fc67bd002be612d53f"`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP CONSTRAINT "FK_8501950a64247eb15c7cab9a2b7"`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP CONSTRAINT "FK_98e1ca336038167c7eb48c02582"`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP CONSTRAINT "FK_16aac8a9f6f9c1dd6bcb75ec023"`);
        await queryRunner.query(`ALTER TABLE "divisions" DROP CONSTRAINT "FK_469211a0a03cf8dc332c7655dbb"`);
        await queryRunner.query(`ALTER TABLE "districts" DROP CONSTRAINT "FK_b0f53665358e2fee2fd290d115f"`);
        await queryRunner.query(`ALTER TABLE "upazilas" DROP CONSTRAINT "FK_e04fa8599f5eea91baf26fbbfdb"`);
        await queryRunner.query(`ALTER TABLE "unions" DROP CONSTRAINT "FK_fe9cc1eb5a2e33a6c25f6b81985"`);
        await queryRunner.query(`ALTER TABLE "areas" DROP CONSTRAINT "FK_351582e1a0d6082c7afffbcb48c"`);
        await queryRunner.query(`ALTER TABLE "order_status_history" DROP CONSTRAINT "FK_1ca7d5228cf9dc589b60243933c"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_cb09242a622007b0c0bd5497a94"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_145532db85752b29c57d2b7b1f1"`);
        await queryRunner.query(`ALTER TABLE "seller_products" DROP CONSTRAINT "FK_7023230fa26e66dbbd85329e471"`);
        await queryRunner.query(`ALTER TABLE "seller_products" DROP CONSTRAINT "FK_14e70742d19396508975a0fcdaa"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP CONSTRAINT "FK_89d3fb68538d89f1c1a6517ebe0"`);
        await queryRunner.query(`ALTER TABLE "payout_requests" DROP CONSTRAINT "FK_3ef419037249b077dc92d4aff26"`);
        await queryRunner.query(`ALTER TABLE "product_requests" DROP CONSTRAINT "FK_037ecf1bc89e6345512e996f7c3"`);
        await queryRunner.query(`ALTER TABLE "product_requests" DROP CONSTRAINT "FK_c7059212b768f76435cced0b2dd"`);
        await queryRunner.query(`ALTER TABLE "product_request_history" DROP CONSTRAINT "FK_f5854387110a5fc7780853b5796"`);
        await queryRunner.query(`ALTER TABLE "product_request_history" DROP CONSTRAINT "FK_318eedd1c453ea8ec1cc470650e"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_728447781a30bc3fcfe5c2f1cdf"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_9482e9567d8dcc2bc615981ef44"`);
        await queryRunner.query(`ALTER TABLE "shops" DROP CONSTRAINT "FK_24acfab664c1ee213d7b9afac9c"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_92558c08091598f7a4439586cda"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP CONSTRAINT "FK_c57d19129968160f4db28fc8b28"`);
        await queryRunner.query(`ALTER TABLE "wishlist_items" DROP CONSTRAINT "FK_177397e044732e7e9c0215cd5b7"`);
        await queryRunner.query(`ALTER TABLE "wishlist_items" DROP CONSTRAINT "FK_549f44d8b756e2690deb099f83b"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_1530a6f15d3c79d1b70be98f2be"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_3fffb0be83ac483af3a55f41170"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_9a5f6868c96e0069e699f33e124"`);
        await queryRunner.query(`ALTER TABLE "product_images" DROP CONSTRAINT "FK_4f166bb8c2bfcef2498d97b4068"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_6343513e20e2deab45edfce1316"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_88cea2dc9c31951d06437879b40"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_377d4041a495b81ee1a85ae026"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1559e8a16b828f2e836a231280"`);
        await queryRunner.query(`DROP TABLE "conversation_participants"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f2577d3e847475ecf0f9aefdb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dcb5e8a55a4180e383aafdb193"`);
        await queryRunner.query(`DROP TABLE "category_brands"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b23c65e50a758245a33ee35fda"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87b8888186ca9769c960e92687"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP TABLE "import_logs"`);
        await queryRunner.query(`DROP TYPE "public"."import_logs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."import_logs_mode_enum"`);
        await queryRunner.query(`DROP TABLE "rider_applications"`);
        await queryRunner.query(`DROP TYPE "public"."rider_applications_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e21c5e12c69727386fb27500dd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c13f2e6f1db742e645b919721a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e3f54c991749da6667c10b9ec9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a92777f7512b1712b617dfccad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_814d79bca04105047c96ae13b8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_013ab4bb41831e4684f2f498a6"`);
        await queryRunner.query(`DROP TABLE "demand_events"`);
        await queryRunner.query(`DROP TYPE "public"."demand_events_eventtype_enum"`);
        await queryRunner.query(`DROP TABLE "seller_applications"`);
        await queryRunner.query(`DROP TYPE "public"."seller_applications_status_enum"`);
        await queryRunner.query(`DROP TABLE "banners"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_177183f29f438c488b5e8510cd"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP TABLE "conversations"`);
        await queryRunner.query(`DROP TABLE "coupon_usages"`);
        await queryRunner.query(`DROP TABLE "delivery_status_history"`);
        await queryRunner.query(`DROP TYPE "public"."delivery_status_history_status_enum"`);
        await queryRunner.query(`DROP TABLE "coupons"`);
        await queryRunner.query(`DROP TYPE "public"."coupons_discounttype_enum"`);
        await queryRunner.query(`DROP TABLE "dispute_messages"`);
        await queryRunner.query(`DROP TABLE "deliveries"`);
        await queryRunner.query(`DROP TYPE "public"."deliveries_status_enum"`);
        await queryRunner.query(`DROP TABLE "disputes"`);
        await queryRunner.query(`DROP TYPE "public"."disputes_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."disputes_reason_enum"`);
        await queryRunner.query(`DROP TABLE "flash_sale_items"`);
        await queryRunner.query(`DROP TABLE "flash_sales"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_33206384cc0a56e1d8d0a0cc47"`);
        await queryRunner.query(`DROP TABLE "otps"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3c324ca49dabde7ffc0ef64675"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_427785468fb7d2733f59e7d7d3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b2f7b823a21562eeca20e72b00"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_payment_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_payment_method_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`DROP TABLE "addresses"`);
        await queryRunner.query(`DROP TABLE "countries"`);
        await queryRunner.query(`DROP TABLE "divisions"`);
        await queryRunner.query(`DROP TABLE "districts"`);
        await queryRunner.query(`DROP TABLE "upazilas"`);
        await queryRunner.query(`DROP TABLE "unions"`);
        await queryRunner.query(`DROP TABLE "areas"`);
        await queryRunner.query(`DROP TABLE "order_status_history"`);
        await queryRunner.query(`DROP TYPE "public"."order_status_history_to_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."order_status_history_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."order_status_history_from_status_enum"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP TABLE "seller_products"`);
        await queryRunner.query(`DROP TABLE "inventory"`);
        await queryRunner.query(`DROP TABLE "payout_requests"`);
        await queryRunner.query(`DROP TYPE "public"."payout_requests_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payout_requests_method_enum"`);
        await queryRunner.query(`DROP TABLE "product_requests"`);
        await queryRunner.query(`DROP TYPE "public"."product_requests_status_enum"`);
        await queryRunner.query(`DROP TABLE "product_request_history"`);
        await queryRunner.query(`DROP TYPE "public"."product_request_history_status_enum"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP TABLE "platform_settings"`);
        await queryRunner.query(`DROP TABLE "shops"`);
        await queryRunner.query(`DROP TABLE "wallets"`);
        await queryRunner.query(`DROP TABLE "wallet_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_transactions_type_enum"`);
        await queryRunner.query(`DROP TABLE "wishlist_items"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TYPE "public"."products_status_enum"`);
        await queryRunner.query(`DROP TABLE "product_images"`);
        await queryRunner.query(`DROP TABLE "product_variants"`);
        await queryRunner.query(`DROP TABLE "brands"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TYPE "public"."roles_name_enum"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
    }

}
