export enum DisputeReason {
  DAMAGED = 'DAMAGED',
  MISSING_ITEM = 'MISSING_ITEM',
  NOT_AS_DESCRIBED = 'NOT_AS_DESCRIBED',
  WRONG_ITEM = 'WRONG_ITEM',
  QUALITY_ISSUE = 'QUALITY_ISSUE',
  ITEM_NOT_RECEIVED = 'ITEM_NOT_RECEIVED',
  QUANTITY_ISSUE = 'QUANTITY_ISSUE',
  PAYMENT_ISSUE = 'PAYMENT_ISSUE',
  OTHER = 'OTHER',
}
