export enum ProductRequestStatus {
  PENDING = 'PENDING',
  REVIEWING = 'REVIEWING',
  SEARCHING = 'SEARCHING',
  FOUND = 'FOUND',
  PRODUCT_ADDED = 'PRODUCT_ADDED',
  CUSTOMER_NOTIFIED = 'CUSTOMER_NOTIFIED',
  CLOSED = 'CLOSED',
  REJECTED = 'REJECTED'
}
