export enum ProductStatus {
  DRAFT = 'DRAFT',
  PENDING_REVIEW = 'PENDING_REVIEW',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  PUBLISHED = 'PUBLISHED',
  ACTIVE = 'ACTIVE',
  UNPUBLISHED = 'UNPUBLISHED',
  INACTIVE = 'INACTIVE',
  ARCHIVED = 'ARCHIVED',
}
